name:                catio
version:             0.1.0.0
github:              "pragsmike/catio"
license:             BSD3
author:              "Mike Gallaher"
maintainer:          "pragsmike@gmail.com"
copyright:           "2020 Mike Gallaher"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Experiments in SDR
# category:            Radio

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pragsmike/catio#readme>

dependencies:
- base >= 4.7 && < 5
- hedn >= 0.3.0.0
- text

library:
  source-dirs: src/lua


executables:
  catio-exe:
    main:                Main.hs
    source-dirs:         src/lua
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catio
    - hedn >= 0.3.0.0

tests:
  catio-test:
    main:                Spec.hs
    source-dirs:         test/lua
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - catio

