[[https://www.rtl-sdr.com/big-list-rtl-sdr-supported-software/][Big List of RTLSDR-supported software]]

[[http://www.abclinuxu.cz/blog/jenda/2019/11/gnu-radio-first-steps-a-fm-receiver][FM Receiver in GnuRadio, step by step]]
* [[https://cubicsdr.com/?cat=4][CubicSDR]]
  
  Cross-Platform Software-Defined Radio Application.
  CubicSDR is the software portion of Software Defined Radio. 
  
  [[https://cubicsdr.readthedocs.io/en/latest/][CubicSDR Manual]]
  
  
[[https://github.com/cjcliffe/CubicSDR/releases/tag/0.2.4][CubicSDR Releases]]

* [[https://luaradio.io/new-to-sdr.html][LUAradio]]

LuaRadio has zero dependencies for non-real-time applications, and may otherwise
use liquid-dsp or VOLK for acceleration in real-time applications. liquid-dsp
shares LuaRadio’s affinity for minimal dependencies and making software-defined
radio more accessible to embedded Linux platforms.

* [[https://liquidsdr.org/][liquidsdr]]

[[https://github.com/jgaeddert/liquid-dsp][liquid-dsp]] liquid-dsp is a free and open-source digital signal processing (DSP)
library designed specifically for software-defined radios on embedded platforms.
The aim is to provide a lightweight DSP library that does not rely on a myriad
of external dependencies or proprietary and otherwise cumbersome frameworks. All
signal processing elements are designed to be flexible, scalable, and dynamic,
including filters, filter design, oscillators, modems, synchronizers, complex
mathematical operations, and much more.

* [[https://github.com/pothosware/SoapySDR/wiki][SoapySDR]]
  
The SoapySDR project is an open-source generalized API and runtime library for
interfacing with SDR devices. With SoapySDR, you can instantiate, configure, and
stream with an SDR device in a variety of environments. Most off the shelf SDR
hardware platforms are supported by SoapySDR, and many open source applications
rely on SoapySDR for hardware integration support. In additon, SoapySDR has
bindings for development frameworks like GNU Radio and Pothos.

Part of [[http://www.pothosware.com/][pothos]].

* [[https://github.com/pothosware/PothosCore/wiki][PothosCore]]
  
 The Pothos project is a complete data-flow framework for creating topologies of
 interconnected processing blocks. Topologies can be designed and tested
 graphically, and deployed over a network. The Pothos framework API enables
 users to quickly create custom processing blocks with minimal boiler-plate.
 Processing blocks can support computational offload and integration with SoC
 and DMA devices. The project also has a diverse set of processing and hardware
 support toolkits.

 
* [[https://redhawksdr.org/][RedHawk]]
  
  RedHawk is an "enterprise" implementation of composable SDR blocks.
  Besides the obvious implementation of composable blocks, RedHawk
  is concerned with practical issues that arise when systems are large,
  distributed, and long-lived.
  
  RedHawk is based on technologies current in the early 2000's,
  such as Java/CORBA, XML, Eclipse.  At this writing, nearly
  20 years later, most new development uses other choices.
  
  From [[https://redhawksdr.org/2.2.6/manual/][RedHawk 2.2.6 manual]]:

  REDHAWK is a software framework designed to support the design, development,
  deployment, management, upgrade, and recycling of real-time distributed
  applications as well as the systems that run them.

  

* Others
  
[[https://github.com/ha7ilm/csdr][csdr]] is a command line tool to carry out DSP tasks for Software Defined Radio.
It can be used to build simple signal processing flow graphs, right from the
command line.


[[https://batchdrake.github.io/SigDigger/][SigDigger]]

[[https://github.com/kpreid/shinysdr][ShinySDR]]

[[http://www.mike-stirling.com/redmine/projects/webradio][WebRadio]]

A [[http://www.websdr.org/][WebSDR]] is a Software-Defined Radio receiver connected to the internet,
allowing many listeners to listen and tune it simultaneously. SDR technology
makes it possible that all listeners tune independently, and thus listen to
different signals...

[[https://eshail.batc.org.uk/nb/][Qatar-OSCAR 100 Narrowband WebSDR]]
 This WebSDR, hosted at Goonhilly Earth Station in Cornwall, enables you to listen to the Qatar-OSCAR 100 Narrow band transponder onboard the Es'hail-2 satellite. 

